replicaCount: 1

## pgAdmin4 container image
##
image:
  registry: docker.io
  repository: dpage/pgadmin4
  tag: "8.6"
  pullPolicy: IfNotPresent

## Deployment annotations
annotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: http
  # targetPort: 4181 To be used with a proxy extraContainer
  portName: http

  annotations: {}
   
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  
  name: ""


strategy: {}
 
serverDefinitions:
  ## If true, server definitions will be created
  ##
  enabled: true

  servers: |-
    "1": {
      "Name": "UAT",
      "Group": "Servers",
      "Port": 5432,
      "Username": "db",
      "Host": "server.uat",
      "SSLMode": "prefer",
      "MaintenanceDB": "db",
      "PassFile": "/var/lib/pgadmin/storage/pgadmin/file.pgpass"
    },
    "2": {
      "Name": "DEV",
      "Group": "Servers",
      "Port": 5432,
      "Username": "db",
      "Host": "server.dev",
      "SSLMode": "prefer",
      "MaintenanceDB": "db",
      "PassFile": "/var/lib/pgadmin/storage/pgadmin/file.pgpass"
    }

networkPolicy:
  enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: pgadmin.netsnek.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: photonq-tls
      # hosts:
      #   - pgadmin.host.net

# Additional config maps to be mounted inside a container
# Can be used to map config maps for sidecar as well
extraConfigmapMounts: []

extraSecretMounts:
  # - name: config-local
  #   secret: pgadmin4-config
  #   subPath: config_local.py
  #   mountPath: "/pgadmin4/config_local.py"
  #   readOnly: true
  # - name: pgpassfile
  #   secret: pgpassfile
  #   subPath: pgpassfile
  #   mountPath: "/var/lib/pgadmin/storage/pgadmin/file.pgpass"
  #   readOnly: true
  - name: certs
    secret: zitadel-pgadmin-cert
    mountPath: "/var/lib/pgadmin/storage/pgadmin/"
    readOnly: true

existingSecret: ""

env:
  # can be email or nickname
  pgpassfile: /var/lib/pgadmin/storage/pgadmin/file.pgpass
  email: admin@netsnek.com
  password: SuperSecret
  
  enhanced_cookie_protection: "False"
persistentVolume:
  
  enabled: true

  annotations: {}

  accessModes:
    - ReadWriteOnce

  size: 10Gi

securityContext:
  runAsUser: 5050
  runAsGroup: 5050
  fsGroup: 5050

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 3

VolumePermissions:
  ## If true, enables an InitContainer to set permissions on /var/lib/pgadmin.
  ##
  enabled: true

## Additional InitContainers to initialize the pod
##
extraInitContainers: |
  - name: add-folder-for-pgpass
    image: "dpage/pgadmin4:4.23"
    command: ["/bin/mkdir", "-p", "/var/lib/pgadmin/storage/pgadmin"]
    volumeMounts:
      - name: pgadmin-data
        mountPath: /var/lib/pgadmin
    securityContext:
      runAsUser: 5050

containerPorts:
  http: 80

resources:
 
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 150m
    memory: 400Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

## Pod affinity
##
affinity: {}

## Pod annotations
##
podAnnotations: {}

## Pod labels
##
podLabels: {}
  # key1: value1
  # key2: value2

init:
  ## Init container resources
  ##
  resources: {}

## Define values for chart tests
test:
  ## Container image for test-connection.yaml
  image:
    registry: docker.io
    repository: busybox
    tag: latest
  ## Resources request/limit for test-connection Pod
  resources: {}

  securityContext:
    runAsUser: 5051
    runAsGroup: 5051
    fsGroup: 5051
