apiVersion: v1
metadata:
  name: pgadmin4-config
type: Opaque
stringData:
  config_local.py: |-
    MASTER_PASSWORD_REQUIRED = True
    AUTHENTICATION_SOURCES = ['oauth2']
    OAUTH2_AUTO_CREATE_USER = True
    OAUTH2_CONFIG = [
      {
          'OAUTH2_NAME': 'Azure',
          'OAUTH2_DISPLAY_NAME': '******',
          'OAUTH2_CLIENT_ID': '*******',
          'OAUTH2_CLIENT_SECRET': '*********',
          'OAUTH2_TOKEN_URL': '******/oauth2/v2.0/token',
          'OAUTH2_AUTHORIZATION_URL': '*******oauth2/v2.0/authorize',
          'OAUTH2_API_BASE_URL': '*******/oauth2/v2.0/',
          'OAUTH2_USERINFO_ENDPOINT': 'https://graph.microsoft.com/oidc/userinfo',
          'OAUTH2_ICON': 'fa-database',
          'OAUTH2_BUTTON_COLOR': '#0000ff',
          'OAUTH2_SCOPE': 'openid'
      }
    ]
---
apiVersion: v1
kind: Secret
metadata:
  name: pgpassfile
type: Opaque
stringData:
  # https://www.postgresql.org/docs/9.4/libpq-pgpass.html
  pgpassfile: |
    server.uat:#{password.uat}#
    server.dev:#{password.dev}#
    server.prod:#{password.prod}#```