volumePermissions:
  enabled: true
tls:
  enabled: true
  # This should be an existing Kubernetes Secret with your SSL certificates
  certificatesSecret: postgres-cert
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
postgresql:
  extendedConf:
    extra_pg_hba_conf: |
      hostssl all all 0.0.0.0/0 cert clientcert=1
      hostssl all all ::/0 cert clientcert=1
auth:
  postgresPassword: "abc"
