volumePermissions:
  enabled: true
tls:
  enabled: true
  # This should be an existing Kubernetes Secret with your SSL certificates
  certificatesSecret: zitadel-postgres-cert
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
  #certCAFilename: "ca.crt"
auth:
  postgresPassword: "abc"
