volumePermissions:
  enabled: true
tls:
  enabled: true
  # This should be an existing Kubernetes Secret with your SSL certificates
  certificatesSecret: zitadel-postgres-cert
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
primary:
  ## @param primary.pgHbaConfiguration PostgreSQL Primary client authentication configuration
  ## ref: https://www.postgresql.org/docs/current/static/auth-pg-hba-conf.html
  ## e.g:#
  ## pgHbaConfiguration: |-
  ##   local all all trust
  ##   host all all localhost trust
  ##   host mydatabase mysuser 192.168.0.0/24 md5
  ##
  pgHbaConfiguration: |-
    # TYPE     DATABASE      USER       ADDRESS                 METHOD
    hostnossl  all           all        0.0.0.0/0               reject  # must be the 1st line!
    hostssl    all           all        0.0.0.0/0               cert clientcert=verify-full
    hostssl    all           all        ::/0                    cert clientcert=verify-full
    local      all           all                                md5
    host       all           all        127.0.0.1/32            md5
    host       all           all        ::1/128                 md5

auth:
  postgresPassword: "abc"
